# Generated by Django 5.1.4 on 2024-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=10)),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=10)),
                ("rate", models.FloatField()),
                ("total", models.FloatField()),
                ("username", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
